name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install MPI
      run: sudo apt-get install -y mpich

    - name: Install g++
      run: |
        sudo apt-get update
        sudo apt-get install -y g++

    - name: Build MPI program
      run: |
        mpic++ -o my_mpi_program src/main.cpp
        echo "MPI program built successfully"

    - name: Run MPI program
      run: |
        mpirun -np 7 ./my_mpi_program
